/***************************************Provincias**************************************************/
insert into provincias (idprovincia,idpais,nombre,[default]) values (26,1,'Costa Atlántica', 0)
update localidades set idprovincia = 26 where idlocalidad = 26


/********************************************Localidades*******************************************/

--Localidades GBA

insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (191,'Almirante Brown', 1,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (30,'Berazategui', 1,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (31,'Esteban Echeverria', 1,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (32,'Florencio Varela', 1,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (33,'Hurlingam', 1,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (34,'José C. Paz', 1,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (35,'Malvinas Argentinas', 1,0)

--Localidades Capital
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (36,'Abasto', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (37,'Agronomia', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (38,'Almagro', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (39,'Balbanera', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (40,'Barracas', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (41,'Boca', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (42,'Boedo', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (43,'Caballito', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (44,'Centro', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (45,'Colegiales', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (46,'Congreso', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (47,'Constitución', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (48,'Chacarita', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (49,'Flores', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (50,'Floresta', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (51,'Liniers', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (52,'Mataderos', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (53,'Parque Centenario', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (54,'Parque Chacabuco', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (55,'Parque Patricios', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (56,'Paternal', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (57,'Pompeya', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (58,'San Cristobal', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (59,'San Telmo', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (60,'Versailles', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (61,'Villa Crespo', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (62,'Villa del Parque', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (63,'Villa Devoto', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (64,'Villa Gral. Mitre', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (65,'Villa lugano', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (66,'Villa Luro', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (67,'Villa Ortuzar', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (68,'Villa Pueyrredón', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (69,'Villa Real', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (70,'Riachuelo', 3,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (71,'Villa Soldati', 3,0)


-- Localidades Buenos Aires
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (73,'Adolfo Alsina', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (74,'Alberti', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (75,'Arrecifes', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (76,'Ayacucho', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (77,'Azul', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (78,'Bahia Blanca', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (79,'Balcarce', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (80,'Baradero', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (81,'Benito Juarez', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (82,'Berisso', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (83,'Bragado', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (84,'Bolivar', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (85,'Campana', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (86,'Cañuelas', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (87,'Capitan Sarmiento', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (88,'Carlos Casares', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (89,'Carlos Tejedor', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (90,'Carmen de Areco', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (91,'Castelli', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (92,'Colon', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (93,'Brandsen', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (94,'Coronel Dorrego', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (95,'Coronel Pringles', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (96,'Coronel Rosales', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (97,'Coronel Suarez', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (98,'Chacabuco', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (99,'Chascomus', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (100,'Chivilcoy', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (101,'Daireaux', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (102,'Dolores', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (103,'Ensenada', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (104,'Exaltación de la Cruz', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (105,'Florentino Ameghino', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (106,'General Alvear', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (107,'General Arenales', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (108,'General Belgrano', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (109,'General Lamadrid', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (110,'General Las heras', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (111,'General Lavalle', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (112,'General Madariaga', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (113,'General Paz', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (114,'General Pinto', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (115,'General Pueyrredon', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (116,'General Rodriguez', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (117,'General Viamonte', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (118,'General Villegas', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (119,'Guamini', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (120,'Hipolito Irigoyen', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (121,'Junin', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (122,'La Plata', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (123,'Laprida', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (124,'Las Flores', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (125,'Leandro N. Alem', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (126,'Lincoln', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (127,'Loberia', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (128,'Lobos', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (129,'Lujan', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (130,'Magdalena', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (131,'Maipú', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (132,'Mar Chiquita', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (133,'Marcos Paz', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (134,'Mercedes', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (135,'Monte', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (136,'Monte Hermoso', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (137,'Navarro', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (138,'Necochea', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (139,'Ninguno', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (140,'9 de Julio', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (141,'Olavarria', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (142,'Patagones', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (143,'Pehuajo', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (144,'Pellegrini', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (145,'Pergamino', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (146,'Pila', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (147,'Puan', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (148,'Presidente Peron', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (149,'Punta Indio', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (150,'Ramallo', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (151,'Rivadavia', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (152,'Rojas ', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (153,'Roque Perez', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (154,'Saavedra', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (155,'Saladillo', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (156,'Salto', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (157,'Salliquelo', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (158,'San Andres de Giles', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (159,'San Antonio de Areco', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (160,'San Cayetano', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (161,'San Nicolas', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (162,'San Pedro', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (163,'San Vicente', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (164,'Suipacha', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (165,'Tandil', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (166,'Topalque', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (167,'Toldillo', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (168,'Tornquist', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (169,'Trenque Lauquen', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (170,'Tres Arroyos', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (171,'Tres Lomas', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (172,'25 de Mayo', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (173,'Villarino', 2,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (174,'Zarate', 2,0)

--Localidades Costa atlántica
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (175,'Pinamar', 26,1)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (176,'Cariló', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (177,'Valeria del Mar', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (178,'Villa Gesell', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (179,'Mar de las Pampas', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (180,'Mar Chiquita', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (181,'Santa Clara', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (182,'Mar del Plata', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (183,'Miramar', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (184,'Mar del Sur', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (185,'Necochea', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (186,'San Cayetano', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (187,'Orense', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (188,'Claromecó', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (189,'Monte Hermoso', 26,0)
insert into localidades (idlocalidad,nombre,idprovincia,[default]) values (190,'Chapadmalal', 26,0)


/***************************************Barrios**************************************************************/

--Barrios GBA
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (1,'Munro Este',327, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (1,'Munro Oeste',41, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (1,'Olivos Golf',42, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (1,'Olivos Rugby',43, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (1,'V. Martelli - Bº Parque',44, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (3,'Lomas de San Isidro',45, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (4,'Avellaneda',46, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (4,'Cinturón Ecologico',47, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (4,'Crucesita',48, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (4,'Dock Sud',49, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (4,'Gerli',50, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (4,'Piñeiro',51, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (4,'Sarandi',52, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (4,'Villa Dominico',53, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (4,'Wilde',54, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (5,'Aeropuerto',55, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (5,'Ezeiza',56, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (5,'Jorge Canning',57, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (5,'La Union',58, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (5,'Máximo Paz',59, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (5,'Spegazzini',60, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (5,'Tristán Suarez',61, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (6,'Bº San Alberto',62, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (6,'Ituzaingó Norte',63, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (6,'Ituzaingó Sur',64, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (6,'Ituzaingó',65, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (6,'Parque Leloir',66, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (6,'Villa Irupé',67, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (6,'Villa Udaondo',68, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'20 de junio',69, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Aldo Bonzi',70, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'C. Martin Güemes',71, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Ciudad evita',72, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Ciudadela Sur',73, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Gonzalez Catán',74, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Isidro casanova',75, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'La Tablada',76, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Laferrere',77, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Lomas del millón',78, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Lomas del Mirador',79, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Puente Escurra',80, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Rafael Castillo Sur',81, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Ramos Mejía',82, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'San Justo',83, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Tapiales',84, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Villa Celina',85, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Villa Insuperable',86, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Villa Luzuriaga',87, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Villa Madero',88, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (7,'Virrey del Pino',89, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (8,'Gerli',90, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (8,'Lanus',91, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (8,'Lanus Este',92, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (8,'Lanus Oeste',93, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (8,'Monte chingolo',94, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (8,'Remedios de Escalada',95, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (8,'Villa Gral. Belgrano',96, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (8,'Valentín Alsina',97, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (9,'Banfield',98, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (9,'Centenario',99, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (9,'Fiorito',100, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (9,'Lomas de Zamora',101, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (9,'Lavallol',102, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (9,'Temperley',103, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (9,'Turdera',104, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (10,'C. Mariano Acosta',105, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (10,'Ferrari',106, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (10,'Libertad',107, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (10,'Merlo',108, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (10,'Parque San Martín',109, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (10,'Pte. Cascallares',110, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (10,'San A. de Padua',111, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (10,'Zona rural',112, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (11,'B. P. Gaona',113, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (11,'Cuartel V',114, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (11,'Francisco Alvarez',115, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (11,'La Reja',116, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (11,'Moreno',117, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (11,'Paso del Rey',118, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (11,'Trujuy',119, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (11,'Villa Malaver',120, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (11,'Zona Rural',121, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (12,'Castelar',122, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (12,'El Palomar',123, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (12,'Haedo',124, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (12,'Moron',125, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (12,'R. Castillo',126, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (12,'V. Leon',127, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (12,'V. Udaondo',128, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (12,'Villa Sarmiento',129, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Bº Astolfi',130, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Bº los Cachorros',131, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Bº  de Vicenso',132, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Bº Rio Lujan',133, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Bº  Solares Norte',134, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Del Viso',135, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Fátima',136, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'J. Vucetich',137, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'La lonja',138, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Manzanares',139, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Manzone',140, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Mf. Savio Oeste',141, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Pilar',142, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Pte. Derqui',143, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Santa Teresa',144, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Toro',145, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Villa Rosa',146, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (13,'Zelaya',147, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (14,'Bernal',148, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (14,'Don Bosco',149, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (14,'Espeleta',150, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (14,'Quilmes Este',151, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (14,'Quilmes Oeste',152, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (14,'Quilmes Sur',153, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (14,'San Francisco Solano',154, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (14,'Villa La Florida',155, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (15,'Punta Chica',156, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (15,'Carupa',157, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (15,'Santa Clara',158, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (15,'Vilas',159, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Ayacucho',160, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Billinghurst',161, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Ciudad Jardin',162, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Gral. Guido',163, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'San Andrés ',164, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa Alcorta',165, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Malaver',166, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa Cnel. Zapiola',167, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa Chacabuco',168, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa Godoy Cruz',169, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa Gral. Las Heras',170, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa Gral. Sucre',171, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa Granaderos Gra',172, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa Gregoria Mator',173, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa Libertad',174, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa Lynch',175, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa M. de Aguado',176, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa Maipú',177, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa San Lorenzo',178, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa Yapeyú',179, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (16,'Villa Monteagudo',180, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (17,'Bella Vista',181, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (17,'C. de Mayo',182, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (17,'Muñiz',183, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (17,'San Miguel',184, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'Islas del Delta',185, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'Islas',186, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'B. Pacheco',187, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'B. El Zorzal',188, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'L. Carmelo',189, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'L. Tunas',190, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'B. Caupá',191, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'Ciudad',192, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'Villa La Ñata',193, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'San Marco',194, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'Santa Tersesa',195, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'Santa Francisco',196, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'San Agustin',197, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'San Gabriel',198, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'San Benito',199, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'San Rafael',200, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (18,'La Escondida',201, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (19,'Bº San Luis',202, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (19,'Bº Aranjuez',203, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (19,'Bº Campo Chico',204, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (19,'Bº Loma Verde',205, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (19,'Bº Náutico',206, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (19,'Bº Santa María',207, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (19,'Escobar',208, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (19,'Garin',209, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (19,'Islas del Delta',210, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (19,'Loma Verde',211, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (19,'Maquinista Savio',212, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (19,'Maschwitz',213, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (19,'Matheu',214, 0 )

insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'11 de Septiembre',215, 1 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'Ciudad Jardín',216, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'M. Coronado',217, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'Pablo Podestá',218, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'Villa Bosh',219, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'Palomar',220, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'Caseros',221, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'Ciudadela',222, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'Churruca',223, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'El libertador',224, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'Jose Ingenieros',225, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'Loma Hermosa',226, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'Partido 3 de Febrero',227, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'Remedios de Escalada',228, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'Saenz Peña',229, 0 )

insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (29,'Villa Raffo',231, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (191,'Adrogué',232, 1 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (191,'Bº San jose',233, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (191,'Burzaco',234, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (191,'Claypole',235, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (191,'Glew',236, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (191,'Jose Marmol',237, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (191,'Longchamps',238, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (191,'Malvinas Argentinas',239, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (191,'Ministro Rivadavia',240, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (191,'Partido Alte. Bron',241, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (191,'Rafael Calzada',242, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (191,'San Francisco Solano',243, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (191,'Zona Rural',244, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (30,'Berazategui',245, 1 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (30,'Carlos Sourigues',246, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (30,'El Pato',247, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (30,'Hudson',248, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (30,'Jose M. Gutierrez',249, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (30,'Pereyra',250, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (30,'Pereyra Iraola',251, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (30,'Platanos',252, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (30,'Ranelagh',253, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (30,'Villa España',254, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (30,'Zona Rural',255, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (31,'9 de Abril',256, 1 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (31,'Canning',257, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (31,'Ezeiza',258, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (31,'El Jaguel',259, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (31,'I. Budge',260, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (31,'Longchamps',261, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (31,'Luis Guillon',262, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (31,'Monte Grande',263, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (31,'P. San Sebastian',264, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (31,'Pda. Union Ferroviaria',265, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (31,'Santa Catalina',266, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (32,'Bosques',267, 1 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (32,'Estanislao Cavalloz',268, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (32,'Florencio Varela',269, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (32,'Gobernador Julio A.',270, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (32,'Ingeniero Juan Allan',271, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (32,'La Capilla',272, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (32,'La Carolina',273, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (32,'Santa Rosa',274, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (32,'Villa Brown',275, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (32,'Villa San Luis',276, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (32,'Villa Vatteone',277, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (33,'Hurlingam',278, 1 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (33,'Villa Tesei',279, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (33,'William Morris',280, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (34,'José C. Paz',281, 1 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (34,'San Miguel',282, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (34,'Tortuguitas',283, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (34,'Vucetich',284, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (35,'Gran Bourg',285, 1 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (35,'Ingeniero Pablo Nogues',286, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (35,'Los Polvorines',287, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (35,'Sordeaux',288, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (35,'Tortuguitas',289, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (35,'Villa de Mayo',290, 0 )

--Barrios Capital
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (20,'Recoleta',291, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (24,'Belgrano centro',292, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (24,'Belgrano Chico',293, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (24,'Belgrano R',294, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (24,'Barrancas',295, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (24,'Las Cañitas',296, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (25,'Palermo Viejo',305, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (25,'Palermo Chico',306, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (25,'Botanico',307, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (25,'Palermo Hollywood',308, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (25,'Palermo Soho',309, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (39,'Once',297, 1 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (44,'Puerto Madero',298, 1 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (44,'Catalinas',299, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (44,'Tribunales',300, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (44,'Microcentro',301, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (44,'Monserrat',302, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (44,'Retiro',303, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (44,'San Nicolás',304, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (28,'Bº P. Urquiza',310, 1 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (28,'P. Chas',311, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (28,'Urquiza R.',312, 0 )

--Barrios Partido de la costa
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'Aguas Verdes',313, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'Costa del Este',314, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'Costa Esmeralda',315, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'La Lucila',316, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'Las Toninas',317, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'Mar de Ajó',318, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'Mar Azul',319, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'Mar del Tuyú',320, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'Montecarlo',321, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'Nueva Atlantis',322, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'Pinar del Sol',323, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'San Bernardo',324, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'San Clemente del Tuyu',325, 0 )
insert into barrios (idlocalidad,nombre,idbarrio,[default]) values (26,'Santa Teresita',326, 0 )


/**********************Asociar Barrios a localidades sin barrios*******************************************/

declare @idBarrio int
select @idbarrio = max(idbarrio) from barrios

insert into barrios (idbarrio, nombre, [default],idlocalidad) (
select @idbarrio + (SELECT COUNT(*) FROM localidades e2 WHERE e2.idlocalidad <= e.idlocalidad and e2.idlocalidad not in (select idlocalidad from barrios)) as IdBarrio  ,e.nombre,1,e.idlocalidad from localidades e where e.idlocalidad not in (select idlocalidad from barrios)
)

/****************************** Poner barrio por default a localidad ***************************************/

update barrios set [default] = 1 where idbarrio in (
select min(b.idbarrio) as idbarrio from barrios b where b.idlocalidad not in( select idlocalidad from barrios where [default] = 1) group by b.idlocalidad
)

/******************** Poner localidad por default a provincia ************************************************/

update localidades set [default] = 1 where idlocalidad in (
select min(l.idlocalidad) idlocalidad from localidades l where l.idprovincia not in( select idprovincia from localidades where [default] = 1) group by l.idprovincia
)