/*
   Domingo, 20 de Abril de 2008 02:35:35 p.m.
   Usuario: 
   Servidor: EMILIOMOVIL
   Base de datos: InmobiliariaDb
   Aplicación: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
CREATE TABLE dbo.Monedas
	(
	IdMoneda int NOT NULL,
	Nombre nvarchar(50) NOT NULL,
	Simbolo nvarchar(15) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Monedas ADD CONSTRAINT
	PK_Monedas PRIMARY KEY CLUSTERED 
	(
	IdMoneda
	) ON [PRIMARY]

GO
COMMIT
