/*
   Domingo, 20 de Abril de 2008 02:41:38 p.m.
   Usuario: 
   Servidor: EMILIOMOVIL
   Base de datos: InmobiliariaDb
   Aplicación: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
CREATE TABLE dbo.Provincias
	(
	IdProvincia int NOT NULL,
	Nombre nvarchar(150) NOT NULL,
	[Default] bit NOT NULL,
	IdPais int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Provincias ADD CONSTRAINT
	PK_Provincias PRIMARY KEY CLUSTERED 
	(
	IdProvincia
	) ON [PRIMARY]

GO
ALTER TABLE dbo.Provincias ADD CONSTRAINT
	FK_Provincias_Paises FOREIGN KEY
	(
	IdPais
	) REFERENCES dbo.Paises
	(
	IdPais
	)
GO
COMMIT
