//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3603.
// 
#pragma warning disable 1591

namespace GI.Managers.WebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using GI.BR.Propiedades.Tranasacciones;
    using GI.BR.Clientes;
    using System.Reflection;
    using GI.BR.Propiedades;
    using GI.BR.Propiedades.Galeria;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PropiedadesServicioSincSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MemberInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cliente))]
    public partial class PropiedadesServicioSinc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RecuperarTransaccionesPendientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransaccionProcesadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarPropiedadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IngresarPropiedadOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarFotoAGaleriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarFotoPropiedadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PropiedadesServicioSinc() {
            this.Url = global::GI.Managers.Properties.Settings.Default.GI_Managers_WebService_PropiedadesServicioSinc;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RecuperarTransaccionesPendientesCompletedEventHandler RecuperarTransaccionesPendientesCompleted;
        
        /// <remarks/>
        public event TransaccionProcesadaCompletedEventHandler TransaccionProcesadaCompleted;
        
        /// <remarks/>
        public event ActualizarPropiedadCompletedEventHandler ActualizarPropiedadCompleted;
        
        /// <remarks/>
        public event IngresarPropiedadCompletedEventHandler IngresarPropiedadCompleted;
        
        /// <remarks/>
        public event AgregarFotoAGaleriaCompletedEventHandler AgregarFotoAGaleriaCompleted;
        
        /// <remarks/>
        public event EliminarFotoPropiedadCompletedEventHandler EliminarFotoPropiedadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarTransaccionesPendientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transacciones RecuperarTransaccionesPendientes() {
            object[] results = this.Invoke("RecuperarTransaccionesPendientes", new object[0]);
            return ((Transacciones)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarTransaccionesPendientesAsync() {
            this.RecuperarTransaccionesPendientesAsync(null);
        }
        
        /// <remarks/>
        public void RecuperarTransaccionesPendientesAsync(object userState) {
            if ((this.RecuperarTransaccionesPendientesOperationCompleted == null)) {
                this.RecuperarTransaccionesPendientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarTransaccionesPendientesOperationCompleted);
            }
            this.InvokeAsync("RecuperarTransaccionesPendientes", new object[0], this.RecuperarTransaccionesPendientesOperationCompleted, userState);
        }
        
        private void OnRecuperarTransaccionesPendientesOperationCompleted(object arg) {
            if ((this.RecuperarTransaccionesPendientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarTransaccionesPendientesCompleted(this, new RecuperarTransaccionesPendientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransaccionProcesada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TransaccionProcesada(Transaccion Transaccion) {
            this.Invoke("TransaccionProcesada", new object[] {
                        Transaccion});
        }
        
        /// <remarks/>
        public void TransaccionProcesadaAsync(Transaccion Transaccion) {
            this.TransaccionProcesadaAsync(Transaccion, null);
        }
        
        /// <remarks/>
        public void TransaccionProcesadaAsync(Transaccion Transaccion, object userState) {
            if ((this.TransaccionProcesadaOperationCompleted == null)) {
                this.TransaccionProcesadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransaccionProcesadaOperationCompleted);
            }
            this.InvokeAsync("TransaccionProcesada", new object[] {
                        Transaccion}, this.TransaccionProcesadaOperationCompleted, userState);
        }
        
        private void OnTransaccionProcesadaOperationCompleted(object arg) {
            if ((this.TransaccionProcesadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransaccionProcesadaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarPropiedad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarPropiedad(Propiedad Propiedad) {
            object[] results = this.Invoke("ActualizarPropiedad", new object[] {
                        Propiedad});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarPropiedadAsync(Propiedad Propiedad) {
            this.ActualizarPropiedadAsync(Propiedad, null);
        }
        
        /// <remarks/>
        public void ActualizarPropiedadAsync(Propiedad Propiedad, object userState) {
            if ((this.ActualizarPropiedadOperationCompleted == null)) {
                this.ActualizarPropiedadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarPropiedadOperationCompleted);
            }
            this.InvokeAsync("ActualizarPropiedad", new object[] {
                        Propiedad}, this.ActualizarPropiedadOperationCompleted, userState);
        }
        
        private void OnActualizarPropiedadOperationCompleted(object arg) {
            if ((this.ActualizarPropiedadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarPropiedadCompleted(this, new ActualizarPropiedadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IngresarPropiedad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IngresarPropiedad(Propiedad Propiedad) {
            object[] results = this.Invoke("IngresarPropiedad", new object[] {
                        Propiedad});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IngresarPropiedadAsync(Propiedad Propiedad) {
            this.IngresarPropiedadAsync(Propiedad, null);
        }
        
        /// <remarks/>
        public void IngresarPropiedadAsync(Propiedad Propiedad, object userState) {
            if ((this.IngresarPropiedadOperationCompleted == null)) {
                this.IngresarPropiedadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIngresarPropiedadOperationCompleted);
            }
            this.InvokeAsync("IngresarPropiedad", new object[] {
                        Propiedad}, this.IngresarPropiedadOperationCompleted, userState);
        }
        
        private void OnIngresarPropiedadOperationCompleted(object arg) {
            if ((this.IngresarPropiedadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IngresarPropiedadCompleted(this, new IngresarPropiedadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarFotoAGaleria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AgregarFotoAGaleria(Foto Foto, int IdPropiedad) {
            object[] results = this.Invoke("AgregarFotoAGaleria", new object[] {
                        Foto,
                        IdPropiedad});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarFotoAGaleriaAsync(Foto Foto, int IdPropiedad) {
            this.AgregarFotoAGaleriaAsync(Foto, IdPropiedad, null);
        }
        
        /// <remarks/>
        public void AgregarFotoAGaleriaAsync(Foto Foto, int IdPropiedad, object userState) {
            if ((this.AgregarFotoAGaleriaOperationCompleted == null)) {
                this.AgregarFotoAGaleriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarFotoAGaleriaOperationCompleted);
            }
            this.InvokeAsync("AgregarFotoAGaleria", new object[] {
                        Foto,
                        IdPropiedad}, this.AgregarFotoAGaleriaOperationCompleted, userState);
        }
        
        private void OnAgregarFotoAGaleriaOperationCompleted(object arg) {
            if ((this.AgregarFotoAGaleriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarFotoAGaleriaCompleted(this, new AgregarFotoAGaleriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarFotoPropiedad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarFotoPropiedad(int IdFoto) {
            object[] results = this.Invoke("EliminarFotoPropiedad", new object[] {
                        IdFoto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarFotoPropiedadAsync(int IdFoto) {
            this.EliminarFotoPropiedadAsync(IdFoto, null);
        }
        
        /// <remarks/>
        public void EliminarFotoPropiedadAsync(int IdFoto, object userState) {
            if ((this.EliminarFotoPropiedadOperationCompleted == null)) {
                this.EliminarFotoPropiedadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarFotoPropiedadOperationCompleted);
            }
            this.InvokeAsync("EliminarFotoPropiedad", new object[] {
                        IdFoto}, this.EliminarFotoPropiedadOperationCompleted, userState);
        }
        
        private void OnEliminarFotoPropiedadOperationCompleted(object arg) {
            if ((this.EliminarFotoPropiedadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarFotoPropiedadCompleted(this, new EliminarFotoPropiedadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void RecuperarTransaccionesPendientesCompletedEventHandler(object sender, RecuperarTransaccionesPendientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarTransaccionesPendientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarTransaccionesPendientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transaccion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transaccion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void TransaccionProcesadaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ActualizarPropiedadCompletedEventHandler(object sender, ActualizarPropiedadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarPropiedadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarPropiedadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void IngresarPropiedadCompletedEventHandler(object sender, IngresarPropiedadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IngresarPropiedadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IngresarPropiedadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void AgregarFotoAGaleriaCompletedEventHandler(object sender, AgregarFotoAGaleriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarFotoAGaleriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarFotoAGaleriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void EliminarFotoPropiedadCompletedEventHandler(object sender, EliminarFotoPropiedadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarFotoPropiedadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarFotoPropiedadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591