using System;
using System.Collections.Generic;
using System.Text;

namespace GI.DA
{
    public class PedidosData
    {
  

        public bool Actualizar(
            int IdPedido,
            decimal CantidadAmbientesFinal,
            decimal CantidadAmbientesInicial,
            int IdCategoria,
            int IdCliente,
            int Disposicion,
            int EnumEstado,
            bool EsAptoProfesional,
            bool EsDepartamento,
            int IdEstadoPropiedad,
            Type EstadoPropiedad,
            int MetrosConstruiblesFinal,
            int MetrosConstruiblesInicial,
            int MetrosCubiertosFinal,
            int MetrosCubiertosInicial,
            int MetrosTerrenoFinal,
            int MetrosTerrenoInicial,
            int IdTipoPropiedad,
            int TipoZona,
            int IdBarrio,
            int IdLocalidad,
            int IdPais,
            int IdProvincia,
            decimal ImporteFinal,
            int IdMonedaImporteFinal,
            decimal ImporteInicial,
            int IdMonedaImporteInicial)
        {

            //SETEAR VARIABLES NULLEABLES

            return AccesoDatos.ActualizarRegistro(
                "Pedido_Actualizar",
                new object[] {   
                    IdPedido,
                    CantidadAmbientesFinal,
                    CantidadAmbientesInicial,
                    IdCategoria,
                    IdCliente,
                    Disposicion,
                    EnumEstado,
                    EsAptoProfesional,
                    EsDepartamento,
                    IdEstadoPropiedad,
                    EstadoPropiedad.ToString(),
                    MetrosConstruiblesFinal,
                    MetrosConstruiblesInicial,
                    MetrosCubiertosFinal, MetrosCubiertosInicial,
                    MetrosTerrenoFinal, MetrosTerrenoInicial,
                    IdTipoPropiedad,
                    TipoZona,
                    IdBarrio,
                    IdLocalidad,
                    IdPais,
                    IdProvincia,
                    ImporteFinal,
                    IdMonedaImporteFinal,
                    ImporteInicial,
                    IdMonedaImporteInicial },
                new string[] {    
                    "@IdPedido",
                    "@CantidadAmbientesFinal",
                    "@CantidadAmbientesInicial",
                    "@IdCategoria",
                    "@IdCliente",
                    "@Disposicion",
                    "@EnumEstado",
                    "@EsAptoProfesional",
                    "@EsDepartamento",
                    "@IdEstadoPropiedad",
                    "@EstadoPropiedad",
                    "@MetrosConstruiblesFinal",
                    "@MetrosConstruiblesInicial",
                    "@MetrosCubiertosFinal", 
                    "@MetrosCubiertosInicial",
                    "@MetrosTerrenoFinal", 
                    "@MetrosTerrenoInicial",
                    "@IdTipoPropiedad",
                    "@TipoZona",
                    "@IdBarrio",
                    "@IdLocalidad",
                    "@IdPais",
                    "@IdProvincia",
                    "@ImporteFinal",
                    "@IdMonedaImporteFinal",
                    "@ImporteInicial",
                    "@IdMonedaImporteInicial"});
        }

        public int Guardar(
            decimal CantidadAmbientesFinal,
            decimal CantidadAmbientesInicial,
            int IdCategoria,
            int IdCliente,
            int Disposicion,
            int EnumEstado,
            bool EsAptoProfesional,
            bool EsDepartamento,
            int IdEstadoPropiedad,
            Type EstadoPropiedad,
            int MetrosConstruiblesFinal,
            int MetrosConstruiblesInicial,
            int MetrosCubiertosFinal,
            int MetrosCubiertosInicial,
            int MetrosTerrenoFinal,
            int MetrosTerrenoInicial, 
            int IdTipoPropiedad, 
            int TipoZona, 
            int IdBarrio,
            int IdLocalidad,
            int IdPais,
            int IdProvincia,
            decimal ImporteFinal,
            int IdMonedaImporteFinal,
            decimal ImporteInicial,
            int IdMonedaImporteInicial)
        {

            //SETEAR VARIABLES NULLEABLES
            return AccesoDatos.InsertarRegistro(
                "Pedido_Guardar",
                new object[] {   
                    CantidadAmbientesFinal,
                    CantidadAmbientesInicial,
                    IdCategoria,
                    IdCliente,
                    Disposicion,
                    EnumEstado,
                    EsAptoProfesional,
                    EsDepartamento,
                    IdEstadoPropiedad,
                    EstadoPropiedad.ToString(),
                    MetrosConstruiblesFinal,
                    MetrosConstruiblesInicial,
                    MetrosCubiertosFinal, MetrosCubiertosInicial,
                    MetrosTerrenoFinal, MetrosTerrenoInicial,
                    IdTipoPropiedad,
                    TipoZona,
                    IdBarrio,
                    IdLocalidad,
                    IdPais,
                    IdProvincia,
                    ImporteFinal,
                    IdMonedaImporteFinal,
                    ImporteInicial,
                    IdMonedaImporteInicial },
                new string[] {    
                    "@CantidadAmbientesFinal",
                    "@CantidadAmbientesInicial",
                    "@IdCategoria",
                    "@IdCliente",
                    "@Disposicion",
                    "@EnumEstado",
                    "@EsAptoProfesional",
                    "@EsDepartamento",
                    "@IdEstadoPropiedad",
                    "@EstadoPropiedad",
                    "@MetrosConstruiblesFinal",
                    "@MetrosConstruiblesInicial",
                    "@MetrosCubiertosFinal", 
                    "@MetrosCubiertosInicial",
                    "@MetrosTerrenoFinal", 
                    "@MetrosTerrenoInicial",
                    "@IdTipoPropiedad",
                    "@TipoZona",
                    "@IdBarrio",
                    "@IdLocalidad",
                    "@IdPais",
                    "@IdProvincia",
                    "@ImporteFinal",
                    "@IdMonedaImporteFinal",
                    "@ImporteInicial",
                    "@IdMonedaImporteInicial"});
        }
    }
}
